# Generated by Django 4.2.3 on 2023-07-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myjwt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyweight',
            name='saved_at',
            field=models.DateField(verbose_name='記録日'),
        ),
    ]
